window.BERN_LAYERS = [
  {
    "key": "overall",
    "label": "Overall opportunity",
    "shortLabel": "Overall",
    "scoreCol": "uoi_score",
    "rawCol": "uoi_score",
    "rawLabel": "Overall opportunity score",
    "rawUnit": "score",
    "rawDirection": "higher_better",
    "why": "A combined view of access, stability, income, education, and hardship signals.",
    "scoreMeaning": "Higher scores mean stronger overall access and fewer measured barriers."
  },
  {
    "key": "internet",
    "label": "Internet access",
    "shortLabel": "Internet",
    "scoreCol": "norm_broadband",
    "rawCol": "pct_broadband",
    "rawLabel": "Households with home internet",
    "rawUnit": "percent",
    "rawDirection": "higher_better",
    "why": "Home internet affects job search, benefits access, school work, telehealth, and legal self-help.",
    "scoreMeaning": "Higher scores mean more households have home internet."
  },
  {
    "key": "housing",
    "label": "Housing cost pressure",
    "shortLabel": "Housing",
    "scoreCol": "norm_rent_burdened",
    "rawCol": "pct_rent_burdened",
    "rawLabel": "Households with high housing costs",
    "rawUnit": "percent",
    "rawDirection": "higher_worse",
    "why": "High housing costs leave less money for food, transportation, utilities, and emergency expenses.",
    "scoreMeaning": "Higher scores mean fewer households are cost burdened."
  },
  {
    "key": "health",
    "label": "Health insurance coverage",
    "shortLabel": "Insurance",
    "scoreCol": "norm_uninsured",
    "rawCol": "pct_uninsured",
    "rawLabel": "People without health insurance",
    "rawUnit": "percent",
    "rawDirection": "higher_worse",
    "why": "Uninsured residents are more exposed to medical debt and delayed care.",
    "scoreMeaning": "Higher scores mean fewer people are uninsured."
  },
  {
    "key": "hospital",
    "label": "Hospital access",
    "shortLabel": "Hospital",
    "scoreCol": "norm_hospital_access",
    "rawCol": "hospital_distance_mi",
    "rawLabel": "Miles to nearest hospital",
    "rawUnit": "miles",
    "rawDirection": "higher_worse",
    "why": "Longer distance to a hospital can make emergency care and follow-up care harder to reach.",
    "scoreMeaning": "Higher scores mean the tract is closer to a hospital."
  },
  {
    "key": "poverty",
    "label": "Poverty",
    "shortLabel": "Poverty",
    "scoreCol": "norm_poverty",
    "rawCol": "pct_poverty",
    "rawLabel": "People below the poverty line",
    "rawUnit": "percent",
    "rawDirection": "higher_worse",
    "why": "Poverty is a direct signal of economic stress and eligibility pressure for support services.",
    "scoreMeaning": "Higher scores mean lower poverty rates."
  },
  {
    "key": "income",
    "label": "Household income",
    "shortLabel": "Income",
    "scoreCol": "norm_income",
    "rawCol": "median_hh_income",
    "rawLabel": "Median household income",
    "rawUnit": "currency",
    "rawDirection": "higher_better",
    "why": "Income helps identify where households have more or less room to absorb financial shocks.",
    "scoreMeaning": "Higher scores mean higher median household incomes."
  },
  {
    "key": "disability",
    "label": "Disability-related barriers",
    "shortLabel": "Disability",
    "scoreCol": "norm_disability",
    "rawCol": "pct_disability",
    "rawLabel": "People living with a disability",
    "rawUnit": "percent",
    "rawDirection": "higher_worse",
    "why": "Disability can increase the need for accessible services, transportation support, and benefits navigation.",
    "scoreMeaning": "Higher scores mean a lower measured disability-related barrier rate."
  },
  {
    "key": "education",
    "label": "Education",
    "shortLabel": "Education",
    "scoreCol": "norm_hs_or_higher",
    "rawCol": "pct_hs_or_higher",
    "rawLabel": "Adults with high school or higher",
    "rawUnit": "percent",
    "rawDirection": "higher_better",
    "why": "Educational attainment is connected to employment options, income, and navigation of institutions.",
    "scoreMeaning": "Higher scores mean more adults have at least a high school credential."
  },
  {
    "key": "snap",
    "label": "SNAP reliance",
    "shortLabel": "SNAP",
    "scoreCol": "norm_snap",
    "rawCol": "pct_snap",
    "rawLabel": "Households receiving SNAP",
    "rawUnit": "percent",
    "rawDirection": "higher_worse",
    "why": "SNAP use can point to food insecurity and household income stress.",
    "scoreMeaning": "Higher scores mean lower SNAP reliance."
  },
  {
    "key": "unemployment",
    "label": "Unemployment",
    "shortLabel": "Jobs",
    "scoreCol": "norm_unemployment",
    "rawCol": "unemployment_rate",
    "rawLabel": "Unemployment rate",
    "rawUnit": "percent",
    "rawDirection": "higher_worse",
    "why": "Unemployment is a strong signal of near-term financial instability.",
    "scoreMeaning": "Higher scores mean lower unemployment."
  },
  {
    "key": "eviction",
    "label": "Eviction pressure",
    "shortLabel": "Eviction",
    "scoreCol": "eviction_resilience_score",
    "rawCol": "eviction_risk_score",
    "rawLabel": "Eviction pressure score",
    "rawUnit": "score",
    "rawDirection": "higher_worse",
    "why": "This proxy combines rent burden, poverty, SNAP reliance, and unemployment to flag instability.",
    "scoreMeaning": "Higher scores mean stronger resilience against eviction pressure."
  }
];
